---
- name: Drupal 8 installation.
  hosts: drupal
  vars:
      dedicated_id: 1111
  become: yes
  tasks:
    - name: Update the package index
      apt:
        update_cache: yes
      run_once: true
    - name: Ensure that net-tools packege is installed
      apt:
        name: net-tools
        state: present
    - name: Ensure php libraries are installed
      apt:
        pkg:
        - php7.2
        - php7.2-mbstring
        - php7.2-mysql
        - php7.2-xml
        - php7.2-zip
        - php7.2-bz2
        - php7.2-bcmath
        - php7.2-curl
        - php7.2-fpm
        - php7.2-gd
        - php7.2-imap
        state: present
    - name: Ensure the server MySQL is installed
      apt:
        name: mysql-server
        state: present
    - name: Ensure the web server Apache2 is installed
      apt:
        name: apache2
        state: present
    - name: Ensure group "tomtom" exists
      group:
        name: tomtom
        gid: "{{ dedicated_id }}"
        state: present
    - name: Ensure if user "tomtom" exists
      user:
        name: tomtom
        uid: "{{ dedicated_id }}"
        shell: /bin/bash
        group: tomtom
        append: yes
    - name: Ensure if user "tomtom.dev" exists
      user:
        name: tomtom.dev
        uid: "{{ dedicated_id }}"
        home: /home/tomtom
        shell: /bin/bash
        group: tomtom
        append: yes
        non_unique: yes
    - name: Updating bash profile for account "tomtom"
      blockinfile:
        path: /home/tomtom/.profile
        block: |
          USER=tomtom
          SUDO_USER=root
          SUDO_UID=0
          USERNAME=tomtom
          MAIL=/var/mail/tomtom
          LC_IDENTIFICATION=nl_NL.UTF-8
          LANG=en_US.UTF-8
          LC_MEASUREMENT=nl_NL.UTF-8
          SHLVL=2
          #LOGNAME=tomtom
          SUDO_GID={{ dedicated_id }}
    - name: Updating .bashrc file for account "tomtom"
      blockinfile:
        path: /home/tomtom/.bashrc
        block: |
          if [[ "$LOGNAME" == *dev ]]; then
            BASH_ENV=/mnt/users/tomtom/dev.shell
          elif [[ "$LOGNAME" == *test ]]; then
            BASH_ENV=/mnt/users/tomtom/test.shell
          fi
          if [ -n "$BASH_ENV" ]; then . "$BASH_ENV"; fi
    - name: Ensure if exists a directory "/mnt/users/tomtom"
      file:
        path: /mnt/users/tomtom
        state: directory
        owner: tomtom
        group: tomtom
        mode: 0775
    - name: Create a file dev.shell with content
      copy:
        dest: "/mnt/users/tomtom/dev.shell"
        content: |
          #!/bin/sh
          #
          # Configure the process environment for tomtom.dev.
          #
          # Source this script without arguments to modify the current shell environment.
          # Run this script with arguments to run a program with the environment.

          export USER=tomtom
          export HOME=/home/tomtom
          export PATH=/usr/bin/php:/usr/local/drush8/drush:/usr/local/bin:$PATH

          export AH_REALM=prod
          export AH_SITE_NAME=tomtomdev
          export AH_APPLICATION_UUID=dbe1ebb8-dc72-4223-a4d1-c4d86a59e21e
          export AH_SITE_GROUP=tomtom
          export AH_SITE_ENVIRONMENT=dev
          export AH_CURRENT_REGION=eu-central-1
          export DRUSH_LAUNCHER_FALLBACK=/usr/local/drush8/drush

          export ACQUIA_HOSTING_DRUPAL_LOG=/var/log/sites/tomtom.dev/logs/staging-21151/drupal-requests.log
          export AH_NON_PRODUCTION=1
          export TEMP=/mnt/tmp/tomtomdev
          export TMPDIR=/mnt/tmp/tomtomdev

          if [ $# -gt 0 ]; then
          exec "$@"
          fi
