---
- name: Drupal 8 installation.
  hosts: drupal
  become: yes
  # remote_user: root
  tasks: 
    - name: Update the package index
      apt:
        update_cache: yes
      run_once: true
    - name: Ensure php is installed
      apt:
        name: php7.2
        # force: yes
        state: present


    