---
- name: Drupal 8 installation.
  hosts: drupal
  vars:
      dedicated_id: 1111
  become: yes
  roles:
    - { role: drupal.php }
    - { role: drupal.mysql }
    - { role: drupal.apache }
    - { role: drupal.users }
  tasks:
